all:
	@make -f Makefile.kammy
	@make -f Makefile.ethdebug

clean:
	@make -f Makefile.kammy clean
	@make -f Makefile.ethdebug clean

objdump:
	@make -f Makefile.kammy objdump
	@make -f Makefile.ethdebug objdump
